### ISSUE TITLE
这个项目还在迭代吗？关于RCON返回被约束每行长度的问题导致的bug

### ISSUE THREAD

**Issue by Tonnp** [VeroFess/PalWorld-Server-Unoffical-Api#30]
使用RCON管理服务器，返回数据存在一行数据最多50字节的bug，导致数据无法获取，比如“showplayer”返回玩家名字[20字节]、playeruid[10字节]、steamid[17字节]，2个逗号 一共49字节是足够的，但是玩家名字采用utf8编码，名字最大20个字符，会变成60字节，直接超过了每行数据50字节的限制，导致pid，steamid被50字节限制截断
获取服务器信息（info）也有同样的问题
不知道增强RCON是否解决这个问题，因为我一直无法编译，不知道能不能提供一个编译好的版本提供下载

Using RCON to manage the server, there is a bug that the return data is up to 50 bytes per line, which makes the data unavailable. For example, "showplayer" returns player name[20 bytes], playeruid[10 bytes], steamid[17 bytes], which is enough for a total of 47 bytes. This is enough, but the player name is encoded in utf8, which is a maximum of 20 characters, and it will become 60 bytes, which directly exceeds the limit of 50 bytes for each line of data, resulting in the pid and steamid being truncated by the 50 byte limit.

**Comment by VeroFess** [comment]
pls check https://github.com/VeroFess/PalWorld-Server-Unoffical-Api/releases
